version: '3'

services:

  node:
    container_name: api
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3000:3000'


  postgres:
    container_name: postgres-db
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-db-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

volumes:
  postgres-db-data:

networks:
  app-connect:
      driver: bridge