FROM node:12

#COPY ./wait-for.sh /opt/app

# Create app directory
WORKDIR /opt/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
#RUN apt-get -q update && apt-get -qy install netcat
#RUN chmod +x ./wait-for.sh
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3333
#CMD [ "npm", "start" ]
#CMD sh -c './wait-for.sh db:5432 -- npm start'