version: "3"

services:
  app:
    build: .
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - postgres
    links:
      - postgres
    #command: ./wait-for.sh db:5432 -- /opt/app/node_modules/.bin/nodemon src/server.js
    command: ./wait-for.sh postgres:5432 -- ./init.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cupoon-db

    volumes:
      - db:/var/lib/data

volumes:
  db:
    driver: local
